name: Frontend CI/CD (AWS S3 + CloudFront)

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        # 만약 env가 필요하다면 여기에 주입 (예: VITE_API_URL)

      # 1. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # 서울 리전

      # 2. 빌드된 dist 폴더를 S3 버킷에 업로드 (기존 파일과 동기화)
      - name: Deploy to Amazon S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
        # --delete 옵션은 깃허브 빌드본엔 없고 S3에만 남아있는 옛날 쓰레기 파일들을 지워주는 역할이야.

      # 3. CloudFront 캐시 무효화 (실시간 반영을 위해 필수)
      - name: CloudFront Invalidate Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFLARE_DISTRIBUTION_ID }} --paths "/*"
